codecov:
  require_ci_to_pass: true

coverage:
  precision: 2 # 45.15313% would become 45.15%
  round: down
  range: "10...100" # Indicating that the color red will start at 10% and be green at 100%
  status:
    project:
      default:
        target: 10%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/localization/**"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true