name: budget_together
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  flutter_riverpod: ^1.0.2
  freezed_annotation: ^1.0.0
  go_router: ^2.5.2
  google_fonts: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  logging: ^1.0.2
  multiple_result: ^1.0.4
  sentry_flutter: ^6.1.2
  supabase_flutter: ^0.2.9
  widgetbook: ^1.0.2
  widgetbook_annotation: ^1.0.0

dev_dependencies:
  all_lint_rules_community: ^0.0.3
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  json_serializable: ^6.1.1
  mocktail: ^0.2.0
  widgetbook_generator: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_intl:
  enabled: true
  arb_dir: lib/localization/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/localization/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
