name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup java environment
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "2.8.0"

      - name: Run flutter pub get
        run: flutter pub get

      - name: Run Flutter format with 120 line length
        run: find . -name "*.dart" -type f  | grep -v "/lib/localization/generated" | xargs flutter format --line-length=120 --dry-run --set-exit-if-changed

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Flutter Analyze
        run: flutter analyze .

      - name: Run import files coverage
        run: |
          chmod +x ./scripts/import_files_coverage.sh
          ./scripts/import_files_coverage.sh budget_together
        shell: bash

      - name: Run tests with coverage flag
        run: flutter test --coverage

      - name: Upload to coverage Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: "./coverage"
          token: ${{ secrets.CODECOV_TOKEN }}