name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "2.5.3"
      - run: flutter pub get
      - run: find . -name "*.dart" -type f  | grep -v "/lib/localization/generated" | xargs flutter format --line-length=120 --dry-run --set-exit-if-changed
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze .
      - run: flutter test --coverage
      - uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: "./coverage/lcov.info"
          min_coverage: 18
          exclude: "**/generated/** **/*.g.dart **/*.freezed.dart"
